version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql-n_1_query:/var/lib/mysql
      - .:/myapp
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: docker_development
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/myapp
  redis:
    image: redis:5.0.3
    volumes:
      - redis-n_1_query:/data
  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    depends_on:
      - app
      - redis
    volumes:
      - .:/myapp
volumes:
  mysql-n_1_query:
  redis-n_1_query:
